name: Deploy Flat Web Prod
on:
  push:
    branches:
      - "stable"
      - "only-deploy-prod-web"
    paths:
      - "config/**"
      - "web/flat-web/**"
      - "packages/flat-components/src/**"
      - "packages/flat-i18n/locales/**"
      - "packages/flat-types/src/**"
      - ".github/workflows/deploy-web-prod.yml"

jobs:
  deploy-flat-web-prod:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          node ./scripts/ci/remove-workspace-packages.js web
          node ./scripts/ci/remove-package-scripts-hooks.js
          # failure automatically retries 3 times
          yarn run bootstrap || yarn run bootstrap || yarn run bootstrap

      - name: Build flat web production
        run: yarn workspace flat-web build -m production

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Reset dockerignore
        run: |
          echo "*" > .dockerignore
          echo "!web/flat-web/dist" >> .dockerignore
          echo "!web/flat-web/deploy/nginx" >> .dockerignore

      - name: Build and push images production
        env:
          COMMIT_SHA_TAG: production-${{ github.sha }}
          LATEST_PROD_TAG: latest
        run: |
          docker build . -f web/flat-web/deploy/Dockerfile -t agoraflat/flat-web:$COMMIT_SHA_TAG -t agoraflat/flat-web:$LATEST_PROD_TAG
          docker push agoraflat/flat-web:$COMMIT_SHA_TAG
          docker push agoraflat/flat-web:$LATEST_PROD_TAG

      - name: Prep helm chart
        run: |
          export APPVERSION=production-${{ github.sha }}
          export CHART=./web/flat-web/helm/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: $APPVERSION/" $CHART

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade flat-web ./web/flat-web/helm --install --wait --atomic --namespace=default
          kubeconfig: '${{ secrets.KUBECONFIG }}'
