name: GitHub Pages
on:
    push:
        branch: "main"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v2
            - name: Install NodeJS ğŸ”¨
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Install and Build ğŸ”§
              # don't install electron and agora
              run: |
                  rm .yarnrc yarn.lock
                  node -e 'var pkg=require("./package.json");pkg.workspaces.packages.pop();pkg=JSON.stringify(pkg,null,4);fs.writeFileSync("package.json",pkg)'
                  yarn install --verbose
                  yarn --cwd ./packages/flat-components build-storybook
            - name: Deploy ğŸš€
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./packages/flat-components/storybook-static
